kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: biz-app
  name: biz-app-admin-rolebinding
subjects:
  - kind: User
    name: biz-app-administrator #name is case sensitive
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: biz-app-admin
  apiGroup: rbac.authorization.k8s.io
