kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: biz-app
  name: company-one-sre-rolebinding
subjects:
  - kind: User
    name: company-one-sre-jane #name is case sensitive
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: company-one-sre
  apiGroup: rbac.authorization.k8s.io
